/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.leqili.calculatorproject;

public class App {
    public static void main(String args[]) {
        App myApp = new App();
        double myAnswer;
        try {
            myAnswer = myApp.answer(2, 2, "+");
            System.out.println("myAnswer is " + myAnswer);
         } catch (Exception e) {
            System.out.println("answer() method threw an exception!");
        }
    }

    public double answer(int firstNumber, int secondNumber, String operation) throws Exception{
        double solutionAnswer;
        if (operation == "+"){
            solutionAnswer = firstNumber + secondNumber;
        }
        else if (operation == "-"){
            solutionAnswer = firstNumber - secondNumber;
        }
        else if (operation == "*"){
            solutionAnswer = firstNumber * secondNumber;
        }
        else if (operation == "/"){
            solutionAnswer = firstNumber / secondNumber;
        }
        else {
            throw new Exception("Bad operator");
        }
        
        return solutionAnswer;
    }
   
    
}
